language: node_js
node_js:
- '6'
before_deploy:
- npm run build
deploy:
  provider: surge
  project: build
  domain: https://kozily.surge.sh
  skip_cleanup: true
  on: master
notifications:
  slack:
    secure: CWLDpPpH6Wl1PIiFdY+g0Due9yv/ggCccRFwSgK7LRdRKNBE7SBzkz8OyXb/k8EfbIHUR7uu0nH4I7oosVSNXJDimkBIJMruYIbGYESCZf62BPvmcYSJK4mkZFVBQ5e3c5C2zaJtLQtP+oGBuLjG2MLGJAhVdQFiXJ22SM3F7z2iODxNZHD8Phj0QpkjggVo/lN+WbWE4DQjLlyq1nFpCc6sOXBwnF/StYwnkotuORDCSqNW2vQn8YZTwOc6aDvukvcSi86xhvhl2TBdxCLY8nDFNs7wBIQ8u41NZ48sAbPLeuPBkzozvNO5Xp8w7NXSNooSYwh46bxdPavoHsswsv1nV+4QDI3i0HPmXvoonwCS4k7z/Hp1+mxnNN4mrO1C1KurN8wFvPu5VoazrXnLwzIiMX9fu3qGaL5AlEuIztnbloyQ+oVfjvXbjPZbJJ3V1yTYToefKVEbcB0S5E8Z029N3Fuue4u7soESxZmf7KWnoX+QzbpP70eX5OvuksR1XNfVm6EGxqmGrPlLHg8eP0bEq2fCY65BFrZNST0Evp3tt4zdVFy5s8XnWEHoFGMVtPjX4b/d/l/q1bY0TvZkR5vi5RHIYeo6svNMGh3jUlMioeiQINzbPW220h3QkzvV0fyO0+4Z8SoEyC36rLPwE+1bUlumfTnk8hP/OuX9kI0=
